include:
  - project: 'xfce/xfce4-dev-tools'
    file: '/ci/build_project.yml'

# esconf distcheck needs a working display/dbus to run tests
# Fake it with xvfb on headless container
distcheck:
  extends: .make
  stage: distcheck
  script:
    - xvfb-run -a make distcheck
